spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect